name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
outputs:
  modifiedFiles:
    description: "The number of files which have been modified"
runs:
  using: 'docker'
  image: 'Dockerfile'
