---
name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace
        id: test
        uses: powerops-mk/replace-action@main
        with:
          filter: "*.txt"
          path: ${{ secrets.TEST_SECRET }}

      - name: Get the output
        run: echo "The ${{ steps.test.outputs.time }}"
