---
name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: powerops-mk/replace-action@main
        with:
          filter: "hello"
          path: "world"
