---
# This is a basic workflow to test test the replace Action
name: "Test Action workflow"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Permissions needed to run the workflow (top level)
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Buils the Docker image
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
 
      # Find and replace the String in files
      - name: Replace      
        uses: powerops-mk/replace-action@50d408aecbd222c2398d63949d8bf960fa259177 # main
        id: replace
        with:
          path: "Test"
          json: ${{ secrets.TEST_SECRET }}
          find: "XX_IP"

      # Get output of replace Action
      - name: Get the output
        run: |
          echo "${{ steps.replace.outputs.count }} files modified"
          cat ./Test/file3.json
          
      - name: tesr
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: 'Mona the Octocat'
